// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRZGOj2NpBFXP8WPNTGv73WlmbDehzlvw',
    appId: '1:752358116779:web:e673757bf30b6ab84a96ee',
    messagingSenderId: '752358116779',
    projectId: 'active-well-468eb',
    authDomain: 'active-well-468eb.firebaseapp.com',
    storageBucket: 'active-well-468eb.appspot.com',
    measurementId: 'G-SJP4RDY8XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkhdM1S5m4eoPSvmsu4qrHnxQoGfjscjw',
    appId: '1:752358116779:android:d196dde493a1db144a96ee',
    messagingSenderId: '752358116779',
    projectId: 'active-well-468eb',
    storageBucket: 'active-well-468eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMdRN0lxErLPmLEzucAbopVd4wkgXI2Z4',
    appId: '1:752358116779:ios:5229d27a0a12a32f4a96ee',
    messagingSenderId: '752358116779',
    projectId: 'active-well-468eb',
    storageBucket: 'active-well-468eb.appspot.com',
    iosBundleId: 'com.example.activewellNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMdRN0lxErLPmLEzucAbopVd4wkgXI2Z4',
    appId: '1:752358116779:ios:71449b9b25d1aeed4a96ee',
    messagingSenderId: '752358116779',
    projectId: 'active-well-468eb',
    storageBucket: 'active-well-468eb.appspot.com',
    iosBundleId: 'com.example.activewellNew.RunnerTests',
  );
}
